### ISSUE TITLE
Cannot be unpacked on Windows

### ISSUE THREAD

**Issue by chorny** [maxmind/WebService-TeamCity#2]
```
Could not open file 'C:\STRAWB~1\cpan\build\tmp-1332\WebService-TeamCity-0.03\t\fixtures\testOccurrences?locator=count:100,start:200,build:(id:667885).json': Invalid argument at C:\Strawberry201\perl\lib/CPAN/Tarzip.pm line 408.
```

**Comment by autarch** [comment]
I think the fix it probably to encode these filenames somehow, maybe with URL-encoding to replace colons.

**Comment by davehorner** [comment]
So this bug makes it impossible to use on windows.

I am assuming this is due to the fixture files which use the filename to store urls.
Using url encoding is not a solution as % is really not an acceptable character either.
WebService-TeamCity/t/fixtures/builds?locator=count:100,start:100.json

Might I suggest changing the filename to a single word (camelCase whatever) description of the test and placing the url within the JSON itself as a testurl property?

Would really like to try this module out but I don't really care for even trying a module if I can't install it across platforms.

Here is what users experience when trying to install WebService::TeamCity.
`
C:\WINDOWS\system32>cpanm  WebService::TeamCity
--> Working on WebService::TeamCity
Fetching http://www.cpan.org/authors/id/M/MA/MAXMIND/WebService-TeamCity-0.03.ta
r.gz ... OK
Could not open file 'C:\Users\dhorner\.cpanm\work\1493132411.6592\WebService-Tea
mCity-0.03\t\fixtures\testOccurrences?locator=count:100,start:200,build:(id:6678
85).json': Invalid argument at C:\Strawberry\perl\site\bin/cpanm line 33.
Could not extract 'WebService-TeamCity-0.03/t/fixtures/testOccurrences?locator=c
ount:100,start:200,build:(id:667885).json' at C:\Strawberry\perl\site\bin/cpanm
line 33.
Configuring WebService-TeamCity-0.03 ... N/A
! The distribution doesn't have a proper Makefile.PL/Build.PL See C:\Users\dhorn
er\.cpanm\work\1493132411.6592\build.log for details.
`

**Comment by oschwald** [comment]
Closing as this distribution is no longer being developed.
